### ISSUE TITLE
Deno and Node do not recognize the module as a ESM, instead recognizes it as a Common JS module.

### ISSUE THREAD

**Issue by zqwitt** [mthh/go-cart-wasm#2]
I have tested this in both Deno @^2.0.0 and Node @^20.0.0

In both environments the module is recognized as a Common JS module and not an ESM.

## Steps to reproduce - Deno example. Node is basically the same

Prerequisite: Install Deno @^2.0.0 and/or Node @^20.0.0

1. Create a deno project using `deno init` or create a node project using `npm init`
2. Install go-cart-wasm: `deno add npm:go-cart-wasm` or `npm install go-cart-wasm`
3. (If using node) update package.json to have `"type":"module"`
4. In the main.ts/js file add the following code: 

```typescript
import initGoCart from "go-cart-wasm";
import data from "./usa.json" with {type:"json"}

const GoCart = await initGoCart();

const fieldName = "population";

const dataCartogram = GoCart.makeCartogram(data, fieldName);

console.log(dataCartogram); // The resulting GeoJSON
```

5. Run `deno run dev` or `node main.js`

## Expected

dataCartogram should print to console:

```sh
{
  type: "FeatureCollection",
  bbox: [
    -125.2065778015873,
    22.514763102895444,
    -66.03812301902907,
    49.25545098395064
  ],
  features: [
    {
      type: "Feature",
      properties: {
        cartogram_id: "1",
        state: "Minnesota",
        adm1_code: "USA-3514",
        population: 5303925,
        area_error: -0.00001
      },
      geometry: { type: "Polygon", coordinates: [ [Array] ] }
    },
    ...
  ]
}
```

## Actual

Deno:
```sh
error: Uncaught SyntaxError: The requested module 'go-cart-wasm' does not provide an export named 'default'
import initGoCart from "go-cart-wasm";
       ^
```

Node:

```sh
import initGoCart from "go-cart-wasm";
       ^^^^^^^^^^
SyntaxError: The requested module 'go-cart-wasm' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:229:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

## Workarounds

Deno:

1. Add `"nodeModulesDir": "auto"` to the `deno.json`
2. Once node module folder is added to the project rename node-modules/go-cart-wasm/dist/go-cart.js to node-modules/go-cart-wasm/dist/go-cart.cjs
3. Import go-cart directly from distribution folder:

```typescript
import initGoCart from "go-cart-wasm/dist/go-cart.cjs";
import data from "./usa.json" with {type:"json"}

const GoCart = await initGoCart();

const fieldName = "population";

const dataCartogram = GoCart.makeCartogram(data, fieldName);

console.log(dataCartogram); // The resulting GeoJSON
```

Node:

1.  Rename node-modules/go-cart-wasm/dist/go-cart.js to node-modules/go-cart-wasm/dist/go-cart.cjs 
2. Import go-cart directly from distribution folder:

```typescript
import initGoCart from "go-cart-wasm/dist/go-cart.cjs";
import data from "./usa.json" with {type:"json"}

const GoCart = await initGoCart();

const fieldName = "population";

const dataCartogram = GoCart.makeCartogram(data, fieldName);

console.log(dataCartogram); // The resulting GeoJSON
```

---

Preferably the distribution should have a .js, .mjs, and .cjs file to allow for the environment to import the desired module type based on the environment config.

**Comment by mthh** [comment]
Thanks for the detailled report :+1: 

I will try to publish a fix tomorrow.
